FROM node:22-slim

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

EXPOSE 4000

# =========================
# 6. Start app
# =========================
CMD ["node", "dist/index.js"]
